name: Update - Broadcaster

on:
  schedule:
    - cron: '15 16 * * *'  # 日本時間の午前1:15に実行（UTCで16:15）
    - cron: '4 16 * * *'  # 日本時間の午前13:15に実行（UTCで4:15）
  workflow_dispatch:

jobs:
  # ビルド
  build-upload:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        repository: MCXboxBroadcast/Broadcaster
        fetch-depth: 0

    - name: Validate Gradle Wrapper
      uses: gradle/actions/wrapper-validation@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: 17
        distribution: temurin

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4
      with:
        gradle-home-cache-cleanup: true

    - name: Build
      run: ./gradlew build

    - uses: actions/upload-artifact@v4
      if: success()
      with:
        name: MCXboxBroadcastExtension
        path: bootstrap/geyser/build/libs/MCXboxBroadcastExtension.jar
        if-no-files-found: error

    - uses: actions/upload-artifact@v4
      if: success()
      with:
        name: MCXboxBroadcastStandalone
        path: bootstrap/standalone/build/libs/MCXboxBroadcastStandalone.jar
        if-no-files-found: error

    - name: Upload Standalone JAR via SFTP
      uses: appleboy/scp-action@v1
      with:
        host: ${{ secrets.GULLONAT_FTP_HOST }}
        port: ${{ secrets.GULLONAT_FTP_PORT }}
        username: ${{ secrets.GULLONAT_FTP_USER }}
        password: ${{ secrets.GULLONAT_FTP_PASS }}
        source: "bootstrap/standalone/build/libs/MCXboxBroadcastStandalone.jar"
        target: "./"
