name: Selenium - G8

on:
  workflow_dispatch:

jobs:
  G8:
    runs-on: ubuntu-latest

    steps:
      - name: リポジトリをチェックアウト
        uses: actions/checkout@v4
        with:
          repository: yamak493/HostVDS
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          path: g8

      - name: pip キャッシュを有効化
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/g8/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Pythonと依存パッケージのセットアップ
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r g8/requirements.txt

      - name: Run multiple commands
        run: |
          sudo apt update
          sudo apt install warp-cli
          warp-cli registration new
          warp-cli connect
        
      - name: Seleniumのテストを実行
        run: |
          source venv/bin/activate
          cd ./g8/root/comment/
          python g8.py
