name: G8+WARP

on:
  workflow_dispatch:

jobs:
  g8warp:
    runs-on: ubuntu-latest

    steps:
      - name: Fetch data from URL
        id: fetch_data
        run: |
          response=$(curl -s http://made-by-free.com/g8.php)
          echo "Response: $response"
          echo "status=$response" >> $GITHUB_ENV

      - name: Stop unless true
        if: env.status != 'true'
        run: |
          echo "処理は停止されます..."
          exit 1

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y curl gnupg lsb-release

      - name: Add Cloudflare's GPG key
        run: |
          curl https://pkg.cloudflareclient.com/pubkey.gpg | sudo gpg --dearmor -o /usr/share/keyrings/cloudflare-warp-archive-keyring.gpg

      - name: Add Cloudflare WARP repository
        run: |
          echo "deb [signed-by=/usr/share/keyrings/cloudflare-warp-archive-keyring.gpg] https://pkg.cloudflareclient.com/ $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/cloudflare-client.list
          sudo apt update

      - name: Install warp-cli
        run: |
          sudo apt install -y cloudflare-warp

      - name: Register and connect WARP
        run: |
          sudo warp-cli --accept-tos registration new
          sudo warp-cli --accept-tos connect

      - name: Private Repository Checkout
        uses: actions/checkout@v4
        with:
          repository: yamak493/HostVDS
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          path: g8

      - name: Enable Cache (pip)
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/g8/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Setup venv+pip
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r g8/requirements.txt
        
      - name: Run selenium
        run: |
          source venv/bin/activate
          cd ./g8/root/comment/
          python g8.py
